[features]
seeds = false
skip-lint = false
[programs.localnet]
blockvault = "NO!"
[programs.devnet]
blockvault = "NO!"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/garvit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
